<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Rejestracja-logowanie</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a5c52671-6adb-4e1e-b1a5-4ef3c7f4703c</testSuiteGuid>
   <testCaseLink>
      <guid>ee2576be-348c-4b56-b4c2-8c393255407b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Rejestracja-logowanie/1Błąd rejestracji (pusty string)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295c937b-83e1-4b46-bc78-4ce949f2c6c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8858e3e9-526c-43b0-b4ff-75380afafffd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Rejestracja-logowanie/2Błąd rejestracji (email już istnieje)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9818aa8-e8ed-4fb9-beef-f27f6eeb33bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34683b91-bda9-420a-bfab-63a391310728</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8cff7922-425f-4237-9b6f-164b01a00369</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Rejestracja-logowanie/3Poprawna rejestracja</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5ba1d0d-0704-46e8-bab5-38263be47769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85215da6-1443-4909-a8c3-92488b3d48cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1bc9f9c3-08fb-482a-89cf-21cb9ac26477</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Rejestracja-logowanie/4Bląd logowania - złe dane</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36087b7f-b244-4eb2-9d57-2693b34f666d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac0a1cf9-17fd-44f6-b96b-3c9c5eda2be7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb5178aa-76fb-4d4b-a44a-56ad9abdba9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca63732a-fe68-4c43-8299-e1cfdfa416e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Rejestracja-logowanie/5Poprawne logowanie</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>555c8332-3859-4cd7-9990-933f7d524459</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa9c2506-9ce5-431d-88f2-1b149497b9e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>300292aa-5168-4b41-a681-afe85580c007</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
